app/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    #path('', views.index, name='home'),
    path('', views.PostListView.as_view(), name='home'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='post'),
    path('new/', views.post_new, name='post_new'),
]

app/hero/urls.py
from django.urls import path 

from . import views

app_name = 'hero'
urlpatterns = [
    path('', views.index, name='index'),

    path('incidents/', views.IncidentListView.as_view(), name='incidents'), 

    path('incident/<int:pk>', views.IncidentDetailView.as_view(), name='incident-detail'),

    path('incident/create', views.IncidentCreateView.as_view(), name='incident-create'),

    path('incident/<int:pk>/update', views.IncidentUpdateView.as_view(), name='incident-update'),

    path('incident/<int:pk>/delete', views.IncidentDeleteView.as_view(), name='incident-delete'),

    path('ngos/', views.NgoListView.as_view(), name='ngos'),

    path('ngo/<int:pk>', views.NgoDetailView.as_view(), name='ngo-detail'),

    path('ngo/create/', views.NgoCreate.as_view(), name='ngo-create'),

    path('ngo/<int:pk>/update', views.NgoUpdate.as_view(), name='ngo-update'),

    path('ngo/<int:pk>/delete', views.NgoDelete.as_view(), name='ngo-delete'),

    path('upload/', views.image_upload, name='upload'),

#    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
#
#    path('borrowedbooks/', views.LoanedBooksListView.as_view(), name='borrowed-books'),
#
#    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),

]

app/home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='home'),
    path('bio/', views.BioView.as_view(), name='bio'),
    path('safe/', views.SafeView.as_view(), name='safe'),
    path('fast/', views.FastView.as_view(), name='fast'),
    path('responsive/', views.ResponsiveView.as_view(), name='responsive'),
    path('jobs/', views.JobListView.as_view(), name='jobs'),
    path('job/<int:pk>', views.JobDetailView.as_view(), name='job_detail'),
    path('contact/', views.contact, name='contact'),
    path('success/', views.success, name='success'),
    path('tools/', views.tools, name='tools'), 
    path('languages/', views.languages, name='languages'),
    #path('upload', views.image_upload, name="upload"),
    #path('tools/', views.ToolListView.as_view(), name='tools'),
    #path('tool/<int:pk>', views.ToolDetailView.as_view(), name='tool_detail'),
    #path('languages/', views.LanguageListView.as_view(), name='languages'),
    #path('language/<int:pk>', views.LanguageDetailView.as_view(), name='language_detail'),
]   

app/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('home/', include('home.urls', namespace='home')),
    path('safe/', include('safe_place.urls', namespace='safe')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('hero/', include('hero.urls', namespace='hero')),
    path('upload/', include('upload.urls')),
    path('auth/', include('registration.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='home/')),
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/base.html
<DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!-- Add addiitional CSS in static file -->
    {% block head-meta %}    
    <meta name="keywords" content="portfolio, web dev, django, Be the Hero">
    <meta name="description" content="A Django based Web App of Be The Hero - Application to connect NGOs and other institutions to people who are available to help">
    {% endblock %}


    {% block title %}
        <title>Hero - Portfolio | Bruno Terres</title>
    {% endblock %}


    {% load static %}
    <linK rel="stylesheet" href="{% static 'css/styles.css' %}">
    <linK rel="stylesheet" href="{% static 'css/global.css' %}">
    {% block static %}
    
    {% endblock %}

</head>
<body>

    <div id="menu" class="header">

            <a href="" class="logo">   
                <img src='/mediafiles/logo.svg' alt="Be The Hero" width="100" height="50"/>
            </a>

        <div class="header-right">

            <ul>
                <li><a href="{% url 'hero:index' %}" class="header-link">About</a></li>
                <li><a href="{% url 'hero:ngos' %}" class="header-link">NGOs</a></li>
                <li><a href="{% url 'hero:incidents' %}" class="header-link">Incidents</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
                {% endif %}
            </ul>

        </div>
      
    </div> 

    <div class="container-fluid content-container">
        <div class="row">


                <div class="block-content">
                {% block content %}
                
                {% endblock %}
                </div>
                {% block pagination %}
                    {% if is_paginated %}
                        <div class="pagination">
                            <span class="page-links">
                                {% if page_obj.has_previous %}
                                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                                {% endif %}
                                <span class="page-current">
                                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                </span>
                                {% if page_obj.has_next %}
                                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                                {% endif %}
                            </span>
                        </div>
                    {% endif %}
                {% endblock %}

        </div>
    </div>
</body>
</html>

app/templates/base2.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  {% block head-meta %}
    <meta charset="utf-8" http-equiv="Content-Type" content="text/html; charset=utf-8">
  {% endblock %}

  {% block title %}
    <title>Authentication</title>
  {% endblock %}

  {% load static %}
  {% block style %}
    <link href="{% static 'static/main.css'%}" rel="stylesheet" type="text/css" media="all">
  {% endblock %}
</head>
<body>
  <main>
    <h1 class='homebase'>base</h1>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

app/templates/base_pages.html
<html>
<head>

    <meta charset="utf-8">
    <!-- Add here the kaywords that describe the project -->
    <meta name="keywords" content="portfolio, web dev, django">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block head-meta %}    
    <meta name="keywords" content="portfolio, web dev, django">
    <meta name="description" content="This is Auth, the authentication app of my portfolio">
    {% endblock %}
    
    {% block title %}{% endblock %}

    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/pages.css' %}">
    {% block style %}
    {% endblock %}

</head> 
<body>
        
    {% block header %}

        <div class="header">
          <div class="header-center">
            <a class="logo" href="{% url 'home:home' %}">Home</a>
            <a href="{% url 'home:tools' %}">Tools</a>
            <a href="{% url 'home:languages' %}">Languages</a>
            <a href="{% url 'home:bio' %}">About</a>
          </div>
        </div>

    {% endblock %}

    {% block content %}{% endblock %}

    {% block footer %}{% endblock %}
</body>
</html> 

app/templates/info_missing.html
{% extends "base_home.html" %}

{% block content %}

    <h2>Info Missing</h2>

    <p> Look like you foggot to add your informations</p>
    <p> Go to the Admin's Page to set some infos about your Bio, Jobs, Tools and Languages </p>

{% endblock %}